name: tune_radio
description: Radio app where you can list to radios around the world.

publish_to: 'none'

version: 1.0.0

homepage: https://github.com/arm-software-inc/tuneradio.mobile

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  just_audio: ^0.9.28
  provider: ^6.0.3
  bloc: ^8.0.3
  equatable: ^2.0.3
  sqflite: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  test: ^1.21.1

flutter:
  uses-material-design: true

  assets:
    - images/search.svg

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
